# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Vishwa Patel
tagline:          'Portfolio'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://vishwapatel14.github.io  
baseurl:          ''  #leave empty if hosted on GitHub Pages at username.github.io

author:
  name:           'Vishwa Patel'
  url:            https://yourwebsite.com  # Update to your own URL or GitHub profile

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
